-- MySQL Script generated by MySQL Workbench
-- 05/04/18 20:49:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema tiril
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words` ;

CREATE TABLE IF NOT EXISTS `words` (
  `id` INT NOT NULL,
  `lang` CHAR(5) NOT NULL,
  `word` LONGTEXT NULL,
  PRIMARY KEY (`id`, `lang`));

CREATE UNIQUE INDEX `word_UNIQUE` ON `words` (`word` ASC) ;


-- -----------------------------------------------------
-- Table `translators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `translators` ;

CREATE TABLE IF NOT EXISTS `translators` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `href` LONGTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `translations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `translations` ;

CREATE TABLE IF NOT EXISTS `translations` (
  `id` INT NOT NULL ,
  `lang` CHAR(5) NOT NULL ,
  `word_id` INT NULL ,
  `src_id` INT NULL ,
  `text` LONGTEXT NULL ,
  `hash` VARCHAR(45) NULL ,
  `type` CHAR(20) NULL ,
  PRIMARY KEY (`id`, `lang`)  ,
  CONSTRAINT `to_words`
    FOREIGN KEY (`word_id`)
    REFERENCES `words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_translators`
    FOREIGN KEY (`src_id`)
    REFERENCES `translators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `word_id_idx` ON `translations` (`word_id` ASC)  ;

CREATE INDEX `to_translators_idx` ON `translations` (`src_id` ASC)  ;


-- -----------------------------------------------------
-- Data for table `translators`
-- -----------------------------------------------------
INSERT INTO `translators` (`id`, `description`, `href`) VALUES (0, 'Google Translate', 'https://translate.google.com');
INSERT INTO `translators` (`id`, `description`, `href`) VALUES (1, 'Lexin', 'http://lexin.udir.no');


