name:                tiril
version:             0.1.0.0
github:              "erithion/tiril"
license:             MIT
author:              "Artyom Bondartsov"
maintainer:          "erithion@gmail.com"
copyright:           "2018 Artyom Bondartsov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/tiril#readme>

dependencies:
- base >= 4.7 && < 5
- warp 
- wai
- http-types
- blaze-builder
- utf8-string
- text 
- bytestring
- http-conduit
- parsec 
- hxt 
- unicode-show
- hxt-http
- HDBC
- HDBC-sqlite3

- persistent
- persistent-sqlite
- persistent-template
- esqueleto

- threepenny-gui
- filepath
- mtl
- extra
- async

library:
  source-dirs: src

executables:
  tiril-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: 
#    - -auto-all 
#    - -caf-all
#    - -fforce-recomp
#    - -O2

    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tiril

tests:
  tiril-test:
    main:                Main.hs
    source-dirs:         _test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
#    - -main-is ./_test/Spec.hs
    dependencies:
    - tiril
    - hspec

benchmarks:
  tiril-benchmarks:
    source-dirs: _bench
    main: Main.hs
    dependencies:
    - base
    - criterion
    - tiril
    - deepseq
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N